### ISSUE TITLE
Is this supposed to work for mac os?

### ISSUE THREAD

**Issue by dosentmatter** [jaseg/lolcat#10]
I see that you use memorymapping which is fmemopen for mac os and you ifdef __APPLE__.

I tried building musl with this

    $ git submodule init
    $ git submodule update
    $ make

but I get error: unknown directive
.weak _init

similar to this
http://stackoverflow.com/questions/40225542/can-musl-libc-be-built-on-os-x

That link also says musl can't be built for mac os. Am I doing something wrong? Is there a way to build musl on mac os or is there a workaround to install lolcat?

Is it possible to swap out musl with glibc?

**Comment by jaseg** [comment]
Yes, this is supposed to work on MacOS. The patch adding that support was contributed by someone else, though, and I do not have an instance of MacOS where I could test this.

The use of musl is a workaround for a longstanding bug of glibc on linuxes. Linux seems to be most common among users so the Makefile defaults to the musl build. Try to use the system-libc build instead and it *should* work:
```make lolcat```
(as opposed to the default target, ```make lolcat-static```)

You will have to install the resulting binary manually since the ```install``` target is meant for usual linuxes and I have no idea where stuff is to go on a Mac.

The MacOS-specific part is a workaround since on MacOS the libc is either missing ```fmemopen``` or it was broken, I can't remember right now.

**Comment by dosentmatter** [comment]
Okay, I ran `make lolcat` and it works. Thanks!

Also, what was the reason for the censoring script? I see it reads from stdin and converts the characters to censor characters. Is that all?

**Comment by jaseg** [comment]
> Okay, I ran ```make lolcat``` and it works. Thanks!

Good to know! I'll put that in the README.

> Also, what was the reason for the censoring script? I see it reads from stdin and converts the characters to censor characters. Is that all?

Yes. I found that useful. Should it do more?

**Comment by dosentmatter** [comment]
> Yes. I found that useful. Should it do more?
Nope, just making sure I understood everything that it does. Maybe there should be documentation about it somewhere - in the README or as a --help flag?
