### ISSUE TITLE
lolcat creates a newline at the end of the output

### ISSUE THREAD

**Issue by cheese1** [jaseg/lolcat#26]
eg.:

cat /etc/passwd
...
flatpak:x:946:945:User for flatpak system helper:/:/sbin/nologin
[cheese@localhost ~]$

but (with an empty line after the output)
lolcat /etc/passwd
...
flatpak:x:946:945:User for flatpak system helper:/:/sbin/nologin

[cheese@localhost ~]$

**Comment by cheese1** [comment]
there should be no need for an extra option "-n" to achieve that

**Comment by jaseg** [comment]
Fixed in 9a928b9ff4795dde86b81d4fbad1baf6026b8c9a

**Comment by n-ham** [comment]
Anyone know how to get the Snap version of lolcat-c updated with this fix?

**Comment by scarlion1** [comment]
Although I don't notice this happening with other uses, but seems when `lolcat` is used with bash `PS1` prompt variable, then a newline gets added at the end still?  For example, dosentmatter had to add [a function to remove newline]( https://github.com/dosentmatter/rainbow-bash-prompt/blob/master/.bash_prompt#L101) after running it through `lolcat`, and i'm seeing it too in my prompt, using your latest commits.  Any idea why that happens, how to prevent it?  Thanks

**Comment by jaseg** [comment]
Hmmm.... I noticed a bug with `--invert` that will print an extra newline, but in normal it should not. Can you perhaps give an example of when that happens?

Note that while lolcat should not add a newline at the end, neither will it remove a newline that is already present on its input. I will have a look at this in the next weeks.

**Comment by scarlion1** [comment]
I mainly just noticed: if I take out the call to `__ps1_remove_newline()` at https://github.com/dosentmatter/rainbow-bash-prompt/blob/ae173df8f3ab606678e242b52612410b7e053f69/.bash_prompt#L117, then there is a newline each time `lolcat-c` gets run, which is twice.  So, instead of the prompt+cursor keeping to a single line, the prompt is now 2 lines and the cursor is on the 3rd line:
![image](https://user-images.githubusercontent.com/2446600/206884409-f437067b-3627-44e5-b1c3-ba92427299a7.png)

If I also take out the call to `lolcat-c` from that same line, then the prompt+cursor is back to a single line:
![image](https://user-images.githubusercontent.com/2446600/206884480-a2e4705e-c6dc-4835-a232-a49d05a68539.png)

(again, `lolcat-c` here points to your binary not dosentmatter's, but the results are still the same either way since their version is just a fork from a previous commit of yours)

Not a huge deal obviously since `__ps1_remove_newline()` fixes things, or in my case since my prompt needs to be multiple lines, I just remove the last newline with `sed -z "s/\(.*\)\\n/\1/"`

I was just trying to get rid of unneeded code and came across this and thought it was strange...

**Comment by n-ham** [comment]
Thanks for all of this, I'm flat out ATM but will get onto these issues in
the new year at some point..

As a lolcat fan you may like my digital animations of images
https://n-ham.com/generative_art.html

Nick
