### ISSUE TITLE
Support 24bit truecolor

### ISSUE THREAD

**Issue by Seirdy** [jaseg/lolcat#29]
[roflcat](https://github.com/jameslzhu/roflcat), another alternative to the original ruby version, supports 24bit truecolor with the `-t` or `--truecolor` flag. It would be great to see something like that in this implementation.

**Comment by jaseg** [comment]
:thinking:

That sounds good, but for one thing: Right now, this lolcat is the fastest lolcat around. 24 bit RGB escape sequences are about 3x as long as the current 256-color palette ones are, which in practice will decrease bandwidth. Since this lolcat is already high-rainbowness and 24-bit rainbows would only marginally increase rainbowness I'd prefer to keep the current, faster version.

Also, the 256-color palette is compatible with more terminal emulators.

If you still want this feature though, feel free to open a PR. As long as it's controlled by a default-off flag I'd merge it.

**Comment by Seirdy** [comment]
Once finals are over I might implement this via an `-i`/`--truecolor` CLI flag. I agree that the default should be 256 colors.
